name: Zip and deploy to webstore
on:
    workflow_dispatch:
jobs:
    zip_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: 🚨 Zipping
              run: cd src && zip -r build.zip *

            - uses: trmcnvn/chrome-addon@v2
              name: ✅ Deploying to webstore
              with:
                  extension: bbaegmboolkgheghdaoahaabjnkofmdm
                  zip: src/build.zip
                  client-id: ${{ secrets.CLIENT_ID }}
                  client-secret: ${{ secrets.CLIENT_SECRET }}
                  refresh-token: ${{ secrets.REFRESH_TOKEN }}
