name: Create Archive
on: 
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: install dependencies
      run: npm ci

    - name: build extension
      run: npm run build

    - name: generate archive
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        path: 'dist'
        filename: 'PSExtender.zip'

    - name: create release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: true
        title: Development Build
        files: |
          PSExtender.zip